# Generated by Django 2.0.8 on 2018-11-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_auto_20181125_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='samples',
            name='allowed_memberships',
            field=models.ManyToManyField(to='testing.Membership'),
        ),
    ]
