# Generated by Django 2.0.8 on 2018-11-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_samples_allowed_memberships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Professional', 'pro')], default='Professional', max_length=30),
        ),
    ]
