# Generated by Django 2.0.8 on 2018-12-06 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('testing', '0005_auto_20181128_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Question1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(max_length=255)),
                ('answer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='BooleanAnswer',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testing.Answer')),
                ('answer', models.BooleanField(choices=[(True, 'yes'), (False, 'no')])),
            ],
            bases=('testing.answer',),
        ),
        migrations.CreateModel(
            name='ChoiceAnswer',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testing.Answer')),
                ('answer', models.IntegerField(choices=[(1, 'exactly true'), (2, 'mostly true'), (3, 'mostly untrue'), (4, 'untrue'), (5, "I don't know ")], max_length=1)),
            ],
            bases=('testing.answer',),
        ),
        migrations.CreateModel(
            name='TextAnswer',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testing.Answer')),
                ('answer', models.TextField()),
            ],
            bases=('testing.answer',),
        ),
        migrations.AddField(
            model_name='answer',
            name='question1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.Question1'),
        ),
    ]
