# Generated by Django 2.0.8 on 2018-12-06 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_auto_20181206_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question1',
            name='answer_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'survey'), ('name', 'text answer')), models.Q(('app_label', 'survey'), ('name', 'boolean answer')), models.Q(('app_label', 'survey'), ('name', 'choice answer')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
