# Generated by Django 2.0.8 on 2018-12-08 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0007_auto_20181206_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question1',
            name='answer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
