# Generated by Django 2.0.8 on 2019-06-22 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampling',
            name='control_procedures',
        ),
        migrations.AddField(
            model_name='sampling',
            name='Client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='procedures.Client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sampling',
            name='Cycle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='procedures.Cycle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sampling',
            name='Year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sampling',
            name='Computed_Upper_Exception_Rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sampling',
            name='Number_of_Exceptions',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sampling',
            name='Sample_Exception_Rate',
            field=models.IntegerField(null=True),
        ),
    ]
