# Generated by Django 2.0.8 on 2019-07-12 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0004_auto_20190712_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampling',
            name='Suggested_Sample_Size',
        ),
        migrations.AlterField(
            model_name='deficiency',
            name='datafile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='procedures.DatafileModel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sampling',
            name='Client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='procedures.Client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sampling',
            name='Cycle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='procedures.Cycle'),
            preserve_default=False,
        ),
    ]
