# Generated by Django 2.0.8 on 2019-07-19 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0006_auto_20190712_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('intro_paragraph', models.TextField(null=True)),
                ('audit_objective', models.TextField(null=True)),
                ('scope_paragraph', models.TextField(null=True)),
                ('deficiency', models.TextField(null=True)),
                ('financials', models.TextField(null=True)),
                ('suggestions', models.TextField(null=True)),
                ('opinion_paragraph', models.TextField(null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedures.Client')),
            ],
        ),
        migrations.AlterField(
            model_name='deficiency',
            name='datafile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='procedures.DatafileModel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sampling',
            name='Client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='procedures.Client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sampling',
            name='Cycle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='procedures.Cycle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sampling',
            name='Suggested_Sample_Size',
            field=models.IntegerField(null=True,),
            preserve_default=False,
        ),
    ]
